import Foundation

/// Deterministic population of behavioural traits from an already-generated identity.
///
/// Identity is the substream boundary: adding or changing trait draws cannot consume the stream
/// that chose a person's name, ratings, position, potential, or UUID. Only traits with a live
/// mechanical consumer belong here. The other `Trait` cases remain Future Simulation Contract
/// dependencies until their named systems consume them; populating them now would make them
/// flavor-only data.
enum TraitPopulationGenerator {
    /// Already in `Trait.allCases` order. Add a case only when its mechanical consumer is live.
    ///
    /// **`ironman` and `volatile` activated 2026-08-13**, which is FSC-014's batched slice. Both
    /// consumers were built earlier in this run and both were no-ops on generated rosters until now:
    /// `ironman` shortens what an injury costs (`02` §3.8, `PeopleRules.injuryWeeks`, in the weekly
    /// draw and the in-play one) and `volatile` weights who draws a flag (`02` §3.5) and who turns up
    /// in the discipline file (`02` §5.2). A trait whose consumer exists and whose population does
    /// not is a rating nobody carries — the same shape as the decoration D6 clause 4 forbids,
    /// arriving from the other end.
    ///
    /// **Every root fingerprint moves with this**, which is why it is one slice rather than three:
    /// a player's `traits` array is persisted, so activating a trait changes generated bytes. The
    /// five still absent — `workhorse`, `iceInVeins`, `frontRunner`, `mentor`, `adaptable` — name
    /// systems that do not consume them yet, and populating them would make them the flavour-only
    /// data this file exists to prevent.
    private static let activeTraits: [Trait] = [.ironman, .restless, .volatile]

    static func traits(for id: UUID) -> [Trait] {
        let personSeed = SeededRandom.seed(from: id)
        return activeTraits.filter { trait in
            guard let ordinal = Trait.allCases.firstIndex(of: trait) else { return false }
            var rng = SeededRandom(seed: SeededRandom.derive(
                from: personSeed,
                scope: .personnel,
                ordinal: ordinal
            ))
            return rng.chance(PeopleRules.traitPopulationProbability)
        }
    }
}
