// Test entry point. Add each new suite's runner here.
runSeededRandomTests()
runModelTests()
runGenerationTests()
runDraftOriginTests()
runGameSimulatorTests()
runSeasonTests()
runFrontOfficeTests()
runInteractiveDraftTests()
runArcadeTests()
runInteractiveGameTests()
runRosterMoveTests()
runPracticeSquadCapTests()
runReSignSquadTests()
runDynastyTests()
runCoachCarouselTests()
runCoachTenureTests()
runDeterminismUnderOffseasonTests()
runLegacyTests()
runPersistenceTests()
runSaveQueueTests()
runDesignSystemTests()
runAlmanacTests()
runMatchupOddsTests()
runTeamTintTests()

TestKit.finish()
