// Test entry point. Add each new suite's runner here.
runSeededRandomTests()
runModelTests()
runGenerationTests()
runDraftOriginTests()
runGameSimulatorTests()
runSeasonTests()
runFrontOfficeTests()
runInteractiveDraftTests()
runArcadeTests()
runDynastyTests()
runLegacyTests()
runPersistenceTests()
runDesignSystemTests()

TestKit.finish()
