// Generated by Tools/TeamLogos/generate_catalog.swift. Do not hand-edit.
import Foundation

public enum CoachWorldTeamLogoCatalog {
    /// The mark a team wears, drawn from the set briefed for its nickname.
    ///
    /// Keyed by nickname, not by team identifier. A team identifier is a position in the generated
    /// random stream, so keying on it tied the whole catalogue to one seed and re-keyed it every
    /// time generation moved -- which is how 52 teams came to wear a mark drawn for somebody else.
    /// A nickname comes from a fixed pool, so this resolves the same way at every seed and survives
    /// a change to what generates.
    ///
    /// `nil` when no artwork has been drawn for that nickname yet. The caller falls back to the
    /// initials chip, which is honest: a wrong mark is worse than no mark.
    public static func mark(forNickname nickname: String, teamID: UUID)
        -> CoachWorldAssetReference? {
        guard let drawn = assetNames[nickname], !drawn.isEmpty else { return nil }
        let choice = Int(fingerprint(teamID) % UInt64(drawn.count))
        return CoachWorldAssetReference(stableID: teamID.uuidString, assetName: drawn[choice])
    }

    /// FNV-1a over the identifier's bytes, so two teams sharing a nickname usually differ.
    ///
    /// Bytes, never `hashValue`: `Hasher` is seeded per process, so a hashed choice would move a
    /// team's mark at the next app launch. Same rule the world generator seeds under.
    private static func fingerprint(_ id: UUID) -> UInt64 {
        withUnsafeBytes(of: id.uuid) { bytes in
            bytes.reduce(UInt64(0xcbf2_9ce4_8422_2325)) { hash, byte in
                (hash ^ UInt64(byte)) &* 0x0000_0100_0000_01b3
            }
        }
    }

    private static let assetNames: [String: [String]] = [
        "Anchors": [
            "TeamLogo_34CD7F4894904F32B21A97F2E351FACD",
            "TeamLogo_399815996A7A4926AF49340208D9057A",
            "TeamLogo_4F7B667410DE489087A97ECA11DDFBC3",
        ],
        "Bastions": [
            "TeamLogo_343AE8DE59CC401796B246AE69E744BE",
            "TeamLogo_EACE3C20E05E4B7EB63BC0E56460E8EE",
            "TeamLogo_FCC35CCD6BB6432091909239ECE10D62",
        ],
        "Bulwarks": [
            "TeamLogo_1046C3255F27488E8D1FEFF7F0D1AD41",
            "TeamLogo_46D018BB3BD9422A91A91971012E8834",
            "TeamLogo_4D2BD12BF3B746FE8863CD6973A66EB1",
            "TeamLogo_612FD3E74D0142E9A010EF4B485965F7",
            "TeamLogo_911BB08E62454715A15EA6851AD2F303",
            "TeamLogo_C0A6908AFD4D408AB0BE70A2298C0B70",
            "TeamLogo_E8D76C2DF87A4503A1B5B80193FC4F5B",
        ],
        "Cairns": [
            "TeamLogo_C210B95DB68B4484BCF72A6DBD879E13",
        ],
        "Colliers": [
            "TeamLogo_6504837E4DE44C068C9A2E818B668BC5",
            "TeamLogo_D4F46917036A4BBC9FA198D66B8F1819",
            "TeamLogo_DEC9D295AA774D578CECE3E92EFDC219",
            "TeamLogo_E2034539439C471E82C24E04DCE73B42",
        ],
        "Coopers": [
            "TeamLogo_1032E7BD52E64C0285D44DC399B13B7A",
            "TeamLogo_5318644DEB7C460194AB8E44598540FF",
            "TeamLogo_5413AE6860094F809CAAAF6859C4171F",
            "TeamLogo_695F21FF95444CF3886F0CB071D200A4",
            "TeamLogo_99FD7E6AC4764FA297F389E767D8D29F",
            "TeamLogo_BB6717ED25E74CE3838D9292E41AA8C1",
        ],
        "Curlews": [
            "TeamLogo_16A673C38E4D4C59A0EA2D3047C8D6EA",
            "TeamLogo_A49BA96C86324844A9585A299EEB60A6",
            "TeamLogo_BF72B12052D042A59152136626721018",
        ],
        "Delvers": [
            "TeamLogo_1A6F2FC4094A489BA3110629E8DE90B7",
            "TeamLogo_545D878FD88145B0A7C2F1AC3B3E018E",
            "TeamLogo_DD841C779B26440E8F870DEAD7D7B6C2",
        ],
        "Ferrymen": [
            "TeamLogo_04EF984B6B834A848F5EA9628DED2CFA",
            "TeamLogo_8A6AEF5F61574BFE9B83687324581F8A",
        ],
        "Fletchers": [
            "TeamLogo_1894B47A15D14F0DB847A3B274E237F4",
            "TeamLogo_2B1D0B55B4414D5895D30E4CE876BEDE",
            "TeamLogo_5ECE4678DCAA4412981D396E9EFACE56",
            "TeamLogo_61B8C12C990B4E94B3EBDF2DFEDE632C",
            "TeamLogo_6219C3658D4946BE9C4BD302DF0A90D5",
            "TeamLogo_65AC24FD9E0B4C56A06A53A589DAADD4",
            "TeamLogo_837E01370ECF4655AA236668ED84AA03",
            "TeamLogo_94D568ED1B87419BB8E4005F63171F1F",
            "TeamLogo_B495A8A8AAFA4736875BC4ECD8E1C5DF",
        ],
        "Goshawks": [
            "TeamLogo_14A2B6E262D44F68B5C899DD51B84249",
            "TeamLogo_34D637F4069E4AFF9A76DCE65F6FE606",
            "TeamLogo_5E9D2C1C55DD44DD8EDA81B10532E0B0",
            "TeamLogo_88D0FB28B8354C949FEE25FB63D497FF",
            "TeamLogo_D01A0E1378184053ABDE4C27F590D24E",
            "TeamLogo_FF88B667115540338E70AEFC3087A0F0",
        ],
        "Ironsides": [
            "TeamLogo_00EBE0C02B2B4988A450BB870D6D3881",
            "TeamLogo_0D81D2F903834BD5A74176604D277691",
            "TeamLogo_5C4CE91F969D4A748E1A7E672C9631AB",
            "TeamLogo_5EBFD5563D164AD8B0A96D19F8E15FCC",
            "TeamLogo_96CC1AF0107D42CAA9CE24F829E6018E",
            "TeamLogo_9F0787A83784407FBCDA8A2CDEB855FC",
            "TeamLogo_E9EA791F96C64B1AB9FCFFEAE9DCE398",
            "TeamLogo_F546F1FAFFE746E8ABA4CE7943DE80C1",
        ],
        "Kestrels": [
            "TeamLogo_05BCBD14EF5E47F3926166202C01D839",
            "TeamLogo_48C82AECD9914D9B94201CF73B52E9C5",
            "TeamLogo_69C777D146CB46EF878EC26AAD0E1F04",
            "TeamLogo_7F6BE01D0F634FA994D30E4427168A2B",
            "TeamLogo_900EF64D9234456EAA4ED488C78B968E",
            "TeamLogo_E43B9F36D94A406C9E630D3FA3148E39",
        ],
        "Lodestars": [
            "TeamLogo_0017F958E7D04FFC9EA801A252B40FD6",
            "TeamLogo_57E1B055AFBA4F86931D51D9B1769E46",
            "TeamLogo_DD1EA5692955458882D8C966CF42EB47",
            "TeamLogo_E6308237BA64482D838B97CBAFC0B502",
        ],
        "Martens": [
            "TeamLogo_12F8D33688BE4F10A59A048E58538175",
            "TeamLogo_306B310F484F48B98FC04F76DCE0F51F",
            "TeamLogo_816FF11F0AE24F5980FE1639A5FB2A25",
            "TeamLogo_9BBB69C94FBA4C26BFDF8BAEF98A8682",
            "TeamLogo_C07AC0D116CE4510B26283DB4CAD3E38",
            "TeamLogo_EAB0CED3A080474397CC8211C51F1CC8",
        ],
        "Palisades": [
            "TeamLogo_25EDC7BB3D5F46E4B8C0B1B22D5D190C",
            "TeamLogo_2DF9A813792342959AD954DBC61EC67C",
            "TeamLogo_613F7CE6DAB84D80ABBEDCD2C886A10C",
            "TeamLogo_6E0B4A63CA6848CD8F9D61626462A2B8",
            "TeamLogo_80E65D18532E4D94839D9F2E6DBB81DB",
            "TeamLogo_95192BA1E5B645A494ED5D44E395EA15",
            "TeamLogo_954025C43FE546BAAC1F62CF09765A0F",
        ],
        "Prospectors": [
            "TeamLogo_2558D27E577244D8B37D80260FB47E61",
            "TeamLogo_336989D4A28D41B4902A2A2EF0164C0D",
        ],
        "Quarrymen": [
            "TeamLogo_4D74C0291A7448D9BF51CAEDFCCBEFA0",
            "TeamLogo_CB7833BC70FE42C0943A61D73AADC350",
            "TeamLogo_DCE1435BDA29499895625FEE1BFDE221",
            "TeamLogo_DFD7F1984BC3417D894FAE36E22967DD",
            "TeamLogo_E7F41714098941A4B322379A36119847",
        ],
        "Reapers": [
            "TeamLogo_25ED4D95A91C4D9C9F3F108CCB6ED8C0",
            "TeamLogo_73490D9265A64A96BAFF0C67F093918F",
            "TeamLogo_C1E1DD214DB74A9BB72FE028B4AAA9C3",
            "TeamLogo_D0DAF2DB46BA42B9A89C815B542D85D3",
        ],
        "Riggers": [
            "TeamLogo_30283F8523334C579A31DADB683D35CA",
            "TeamLogo_382E7342881F4EF29D3A47F0A984658D",
            "TeamLogo_DBF4A6963DED4B4DAF876FF2FBDE994E",
        ],
        "Sawyers": [
            "TeamLogo_33D771AF7E1C4C4CBD961BC8AEA568EC",
            "TeamLogo_759E356409AA496B9037952E6830FA52",
            "TeamLogo_90369DB3A0EA40F68A405DEF59CFE630",
        ],
        "Sentinels": [
            "TeamLogo_1982A97FCD2B459BAF2389D5151A9829",
            "TeamLogo_A6E5417A9D724874AAC38CD372E646BB",
        ],
        "Shrikes": [
            "TeamLogo_0FDAFFDF1E0048D68F5298BEC1B9254A",
            "TeamLogo_4025813E0EF74FBAA82187DB4A5D967F",
            "TeamLogo_80E36CC98576453EA822ECBB145E94DD",
        ],
        "Smelters": [
            "TeamLogo_3E7B89997AE846D691FA65C4712CBD1C",
            "TeamLogo_64F5B014D4BE4297A8F1026ACA25D4A6",
            "TeamLogo_A0D5378A462C4791AE53952A79FCCD62",
            "TeamLogo_B6783970BA3D485C815D9A62F25005C9",
            "TeamLogo_D851E5D2C6A440CF83085FA0947078EF",
        ],
        "Stalkers": [
            "TeamLogo_3CC89B98DB124AF5924F434FF612C1E7",
            "TeamLogo_77090443FFE541F884EFD0184B6F7441",
            "TeamLogo_A76F3F73396A4D0AAE5F7D5A4E206897",
            "TeamLogo_ADCDD8604E4C4DDEAF4AF72EDDD40FF9",
        ],
        "Tanners": [
            "TeamLogo_2DBDBC5E18D2417BBC73C6596576F72B",
            "TeamLogo_35A88873B49C4A9CB99A47F75AD6D35F",
            "TeamLogo_633D4024B8D748B6A7CC4D7682EDD614",
            "TeamLogo_A3B3903E148F481A846900002BEB8BBB",
        ],
        "Voyagers": [
            "TeamLogo_4CACCDE7340F4E4F8869031E960CD31E",
            "TeamLogo_75EC4DC65A044142A91EB0F2F30D5ECA",
            "TeamLogo_ABD2FF259964494B86E34B89E24B5348",
            "TeamLogo_B5C9CAB852854CF8951E88C55EBBA97C",
            "TeamLogo_DA7DABF5F0444E05A9064EE7AE778B78",
            "TeamLogo_F9BD5A3A9ED548969CEF085A8A509C2D",
        ],
        "Wardens": [
            "TeamLogo_3D177C44C4CB4FEDBD0EFA4B5B8F71D6",
            "TeamLogo_789772DF0D264FCB87E66FB1B0BCAE2F",
            "TeamLogo_A30D0E61D95A4C4CB20CF43A6943E341",
            "TeamLogo_C9129F1DC49F4FAC8C36CEAAAA0D958F",
        ],
        "Wayfarers": [
            "TeamLogo_4135CA8D38DC4CDEAC7CF4951BC6E52E",
            "TeamLogo_41BE1B2FCD4B4DEFAE039AB87B565BD6",
            "TeamLogo_7DEF46FB180544A39484F2589F1712ED",
            "TeamLogo_A317A3D847BE478B96991FE2861C9E2C",
            "TeamLogo_F565417AC5DA40ACBEF3FE5B0EE0B8F7",
        ],
        "Wreckers": [
            "TeamLogo_15C385432FBB438F9CC626BBB3DD8B38",
            "TeamLogo_161EBDA6B0924127B535359070BDEFBE",
            "TeamLogo_5E8574FC01C24A4686F96B7D135139C5",
            "TeamLogo_74CBDAB262B04A15B1C5547E005A7E4F",
            "TeamLogo_A18D99F90C394357A01D2A968BC6B8C0",
            "TeamLogo_E850EC8C04D84A14989E1DB67F263D24",
        ],
        "Wyverns": [
            "TeamLogo_29A6A1DC04F249E78BF6D6793812399E",
            "TeamLogo_3FCE33B8F5C54D74BB41FB29886AD0C6",
            "TeamLogo_CF442D448E8040458888B1EC5CC934E4",
        ],
    ]

    #if DEBUG
    /// One proof row per mark, named for what it depicts.
    ///
    /// Built from the table rather than listed a second time: the sheet is a look at the artwork,
    /// and a second copy of every asset name is a second thing that can disagree with the first.
    static let proofTeams: [CoachWorldTeamReference] = assetNames.keys.sorted()
        .flatMap { nickname in
            (assetNames[nickname] ?? []).map { asset in
                CoachWorldTeamReference(
                    stableID: asset,
                    name: nickname,
                    abbreviation: String(nickname.prefix(3)).uppercased(),
                    mark: CoachWorldAssetReference(stableID: asset, assetName: asset)
                )
            }
        }
    #endif
}