import Foundation

struct Manifest: Decodable {
    let schemaVersion: Int
    let marks: [Mark]
}

struct Mark: Decodable {
    let nickname: String
    let assetName: String?
    let generationStatus: String
    let humanApproved: Bool
}

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let manifestURL = root.appendingPathComponent("Tools/TeamLogos/manifest.json")
let outputURL = root.appendingPathComponent(
    "Sources/ProFootballCoachUI/TeamLogoCatalog.generated.swift"
)
let manifest = try JSONDecoder().decode(
    Manifest.self,
    from: Data(contentsOf: manifestURL)
)
guard manifest.schemaVersion == 2 else { fatalError("catalogue requires manifest schema 2") }

// Only drawn, adopted artwork reaches the app. A pending record is a brief with no picture behind
// it, and shipping its name would resolve a team to an asset the bundle does not hold.
let drawn = manifest.marks.filter { $0.generationStatus == "approved" && $0.humanApproved }
guard !drawn.isEmpty, drawn.allSatisfy({ $0.assetName != nil }) else {
    fatalError("every approved record must name the asset it was drawn as")
}

var byNickname: [String: [String]] = [:]
for mark in drawn { byNickname[mark.nickname, default: []].append(mark.assetName!) }

let entries = byNickname.keys.sorted().map { nickname in
    let assets = byNickname[nickname]!.sorted()
        .map { "            \"\($0)\"," }
        .joined(separator: "\n")
    return "        \"\(nickname)\": [\n\(assets)\n        ],"
}.joined(separator: "\n")

let source = """
// Generated by Tools/TeamLogos/generate_catalog.swift. Do not hand-edit.
import Foundation

public enum CoachWorldTeamLogoCatalog {
    /// The mark a team wears, drawn from the set briefed for its nickname.
    ///
    /// Keyed by nickname, not by team identifier. A team identifier is a position in the generated
    /// random stream, so keying on it tied the whole catalogue to one seed and re-keyed it every
    /// time generation moved -- which is how 52 teams came to wear a mark drawn for somebody else.
    /// A nickname comes from a fixed pool, so this resolves the same way at every seed and survives
    /// a change to what generates.
    ///
    /// `nil` when no artwork has been drawn for that nickname yet. The caller falls back to the
    /// initials chip, which is honest: a wrong mark is worse than no mark.
    public static func mark(forNickname nickname: String, teamID: UUID)
        -> CoachWorldAssetReference? {
        guard let drawn = assetNames[nickname], !drawn.isEmpty else { return nil }
        let choice = Int(fingerprint(teamID) % UInt64(drawn.count))
        return CoachWorldAssetReference(stableID: teamID.uuidString, assetName: drawn[choice])
    }

    /// FNV-1a over the identifier's bytes, so two teams sharing a nickname usually differ.
    ///
    /// Bytes, never `hashValue`: `Hasher` is seeded per process, so a hashed choice would move a
    /// team's mark at the next app launch. Same rule the world generator seeds under.
    private static func fingerprint(_ id: UUID) -> UInt64 {
        withUnsafeBytes(of: id.uuid) { bytes in
            bytes.reduce(UInt64(0xcbf2_9ce4_8422_2325)) { hash, byte in
                (hash ^ UInt64(byte)) &* 0x0000_0100_0000_01b3
            }
        }
    }

    private static let assetNames: [String: [String]] = [
\(entries)
    ]

    #if DEBUG
    /// One proof row per mark, named for what it depicts.
    ///
    /// Built from the table rather than listed a second time: the sheet is a look at the artwork,
    /// and a second copy of every asset name is a second thing that can disagree with the first.
    static let proofTeams: [CoachWorldTeamReference] = assetNames.keys.sorted()
        .flatMap { nickname in
            (assetNames[nickname] ?? []).map { asset in
                CoachWorldTeamReference(
                    stableID: asset,
                    name: nickname,
                    abbreviation: String(nickname.prefix(3)).uppercased(),
                    mark: CoachWorldAssetReference(stableID: asset, assetName: asset)
                )
            }
        }
    #endif
}
"""

try source.write(to: outputURL, atomically: true, encoding: .utf8)
